### ISSUE TITLE
Android Kotlin Fundamentals codelab: 02.3: Constraint layout using the Layout Editor

### ISSUE THREAD

**Issue by donatelloraphael** [google-developer-training/android-kotlin-fundamentals-apps#108]
**Describe the problem**
In instruction 4, on the code
      `R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
       R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
       R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)`

the references `box_three_text, box_four_text, box_five_text` are unresolved as the references are assigned to variables in another function. Either make variable assignments global or assign them again in the function `makeColored()`.

**In which lesson and step of the codelab can this issue be found?**
Lesson 02.3, Step 12, Instruction 4

**codelab:** android-kotlin-fundamentals

**Comment by noveriuspinem** [comment]
It should be replaced with:
R.id.red_button -> findViewById(R.id.box_three_text).setBackgroundResource(R.color.my_red)
R.id.yellow_button -> findViewById(R.id.box_four_text).setBackgroundResource(R.color.my_yellow)
R.id.green_button -> findViewById(R.id.box_five_text).setBackgroundResource(R.color.my_green)

If the makeColored function takes R.id.red_button as input parameter, Android do not have a clue what other View(s) are. That's why the "Unresolved reference: bla-bla-bla" error comes up.
