### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Haffi921** [google-developer-training/android-kotlin-fundamentals-apps#342]
**In which lesson and step of the codelab can this issue be found?**
Lesson 02.3, Task 12, Step 4

**Describe the problem**
In this step, the buttons are added to a when statement.

They are added with `setBackgroundResource()`. In the previous tasks, the when statement was populated with `setBackgroundColor()` function calls.

The step text is really short and doesn't explain much. There is no explanation to what the difference is between these two functions and why they are being used instead of the others. I believe this would be beneficial to have.

I personally was a bit confused by this and I do not fully comprehend the differences, or what the `setBackgroundResource()` function does.

**codelab:** android-kotlin-fundamentals

**Comment by Osunator** [comment]
You are right man that it doesn't explain much in that step, but there is a reason for the use of "setBackgroundResource()" instead of setBackgroundColor().
If you did the Coding Challenge at Task 9 you have to use setBackgroundResource() to define the images into the TextView, because the images are considered a Resource. And as an image is a resource, when you define the custom colors in variables those are considered Resources, you can't called them using the setBackgroundColor(), it gives and error, you need to use the setBackgroundResource().

**Comment by Haffi921** [comment]
This is great! Yeah, totally explains it. I would therefore suggest this following change to Lesson 02.3, Task 12, Step 4:

> 4. Inside the makeColored() function, add code to change the text views' colors when the user taps the buttons. Previously, we have used `setBackgroundColor()` to change the background color of views but here we need to use `setBackgroundResource()`.
> When you define a custom color in a variable, it is considered a Resource. `setBackgroundColor()` is only used for default colors, like `Color.RED`. Instead, we use `setBackgroundResource()` to set our custom color variable as the view's background resource.
>
> _Note:_ If you did the Coding Challenge in Task 9, you also had to use `setBackgroundResource()` to define the images into the TextView. This is because, just like custom color variables, an image is considered a Resource.
>
> Add the new code above the else statement, as shown:

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
