### ISSUE TITLE
Android Kotlin Fundamentals codelab: "Repository Pattern" Studio project is out of date / deprecated

### ISSUE THREAD

**Issue by christate** [google-developer-training/android-kotlin-fundamentals-apps#856]
Two things:

* first, the download cited is for a large bundle of many projects, unlike all the previous codelabs in this sequence.  The instructions do not make it clear that only the relevant "Repository Pattern" subfolder of the downloaded .zip is to be opened.
* second, the project itself is wildly out of date, to the point that it prompts deprecation warnings in Studio as soon as it is opened.  In particular, it uses the 'kotlin-android-extensions' gradle plugin, which is no longer supported.

The project is so out-of-date that simply opening it the first time in Studio (Electric Eel, current as of this writing) kicked off a Gradle download-and-rebuild sequence that took more than 3 minutes *even on a gigabit fiber internet connection.*

**Comment by ModuleHunter** [comment]
Agree. I was very confused not being able to download only the "DevBytes" folder. I tried to update all dependencies but still got errors about unresolved references (probably because they were removed/renamed in newer versions). I'm still a very beginner at Android development so I'm totally overwhelmed with what to do.
Personally, I recommend to skip this codelab and search for other solutions elsewhere unless you want to spend hours on updating and adjusting all the outdated code yourself.

**Comment by jlulovics** [comment]
Hello! Thank you for your feedback. This codelab is out of date and no longer maintained. Instead, please refer to the [Android Basics with Compose](https://developer.android.com/courses/android-basics-compose/course) course for the latest recommended practices. If you are looking for content on Views, you can check out the [Android Basics in Kotlin](https://developer.android.com/courses/android-basics-kotlin/course) course.
